settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: work_api
    path: .
    commands:
      install:
        status: true
        method: go build -o app.out ./main.go ./app.go
      run:
        status: true
        method: ./app.out
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
        - vendor